export const icons = [
  { id: 1, icon: 'fa-solid fa-mobile-screen', title: 'mobile' },
  { id: 2, icon: 'fa-solid fa-tablet-screen-button', title: 'tablet' },
  { id: 3, icon: 'fa-solid fa-desktop', title: 'desktop' },
  { id: 4, icon: 'fa-solid fa-eye', title: 'preview' },
  { id: 5, icon: 'fa-solid fa-expand', title: 'fullscreen' },
  { id: 6, icon: 'fa-solid fa-code', title: 'view code' },
  { id: 7, icon: 'fa-solid fa-arrow-rotate-left', title: 'undo' },
  { id: 8, icon: 'fa-solid fa-arrow-rotate-right', title: 'redo' },
  { id: 9, icon: 'fa-solid fa-download', title: 'import' },
  { id: 10, icon: 'fa-solid fa-trash-can', title: 'clear canvas' },
  { id: 11, icon: 'fa-solid fa-highlighter', title: 'open style manager' },
  { id: 12, icon: 'fa-solid fa-layer-group', title: 'open layer manager' },
  { id: 13, icon: 'fa-regular fa-square-plus', title: 'open blocks' },
];
